inherit_from:
  - ./default_pending.yml

require:
  - rubocop-github
  - rubocop-performance

Bundler/DuplicatedGem:
  Enabled: true

Bundler/GemComment:
  Enabled: false

Bundler/GemFilename:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Bundler/InsecureProtocolSource:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true

Gemspec/DependencyVersion:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/DuplicatedAssignment:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RubyVersionGlobalsUsage:
  Enabled: false

GitHub/AvoidObjectSendWithDynamicMethod:
  Enabled: true

GitHub/InsecureHashAlgorithm:
  Enabled: true
