inherit_from:
  - ./default_pending.yml

require:
  - rubocop-github
  - rubocop-performance

Bundler/DuplicatedGem:
  Enabled: true

Bundler/GemComment:
  Enabled: false

Bundler/GemFilename:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Bundler/InsecureProtocolSource:
  Enabled: false

