inherit_from:
  - ./default_pending.yml

require:
  - rubocop-github
  - rubocop-performance

Bundler/DuplicatedGem:
  Enabled: true

Bundler/GemComment:
  Enabled: false

Bundler/GemFilename:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Bundler/InsecureProtocolSource:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true

Gemspec/DependencyVersion:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/DuplicatedAssignment:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RubyVersionGlobalsUsage:
  Enabled: false

GitHub/AvoidObjectSendWithDynamicMethod:
  Enabled: true

GitHub/InsecureHashAlgorithm:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/AssignmentIndentation:
  Enabled: false

Layout/BeginEndAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#indent-when-as-start-of-case
  EnforcedStyle: end

Layout/ClassStructure:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/ConditionPosition:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/DotPosition:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLineAfterMultilineCondition:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EmptyLinesAroundBeginBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocArgumentClosingParenthesis:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/IndentationConsistency:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#indentation

Layout/IndentationStyle:
  EnforcedStyle: spaces
  IndentationWidth: 2
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#default-indentation

Layout/IndentationWidth:
  Width: 2
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#default-indentation

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineContinuationSpacing:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineHashKeyLineBreaks:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SingleLineBlockChain:
  Enabled: false

Layout/SpaceAfterColon:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#spaces-operators

Layout/SpaceAfterComma:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#spaces-operators

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#spaces-operators

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#spaces-around-equals

Layout/SpaceAroundKeyword:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#spaces-operators

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: true
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#spaces-operators
  Exclude:
  - "**/*.erb"

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceBeforeSemicolon:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#no-spaces-braces

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#trailing-whitespace

Lint/AmbiguousAssignment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AmbiguousRange:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/BigDecimalNew:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/BooleanSymbol:
  Enabled: false

Lint/CircularArgumentReference:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/ConstantOverwrittenInRescue:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Lint/Debugger:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/DuplicateCaseCondition:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: false

Lint/DuplicateHashKey:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: false

Lint/DuplicateRequire:
  Enabled: false

Lint/DuplicateRescueException:
  Enabled: false

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/EmptyInPattern:
  Enabled: false

Lint/EmptyConditionalBody:
  Enabled: false

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyExpression:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Lint/EmptyInterpolation:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/FlipFlop:
  Enabled: true

Lint/FloatComparison:
  Enabled: false

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: false

Lint/HeredocMethodCallPosition:
  Enabled: false

Lint/IdentityComparison:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/InheritException:
  Enabled: false

Lint/InterpolationCheck:
  Enabled: false

Lint/LambdaWithoutLiteralBlock:
  Enabled: false

Lint/LiteralAsCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/MissingCopEnableDirective:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/MultipleComparison:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Lint/NestedPercentLiteral:
  Enabled: false

Lint/NextWithoutAccumulator:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/NonAtomicFileOperation:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Lint/NumberedParameterAssignment:
  Enabled: false

Lint/OrAssignmentToConstant:
  Enabled: false

Lint/OrderedMagicComments:
  Enabled: false

Lint/OutOfRangeRegexpRef:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#no-spaces-method-parens
  Exclude:
  - "**/*.erb"

Lint/PercentStringArray:
  Enabled: false

Lint/PercentSymbolArray:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/RandOne:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantCopEnableDirective:
  Enabled: false

Lint/RedundantDirGlobSort:
  Enabled: false

Lint/RedundantRequireStatement:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Lint/RedundantWithIndex:
  Enabled: false

Lint/RedundantWithObject:
  Enabled: false

Lint/RefinementImportMethods:
  Enabled: false

Lint/RegexpAsCondition:
  Enabled: false

Lint/RequireParentheses:
  Enabled: true

Lint/RequireRangeParentheses:
  Enabled: false

Lint/RequireRelativeSelfPath:
  Enabled: false

Lint/RescueException:
  Enabled: true

Lint/RescueType:
  Enabled: false

Lint/ReturnInVoidContext:
  Enabled: false

Lint/SafeNavigationChain:
  Enabled: false

Lint/SafeNavigationConsistency:
  Enabled: false

Lint/SafeNavigationWithEmpty:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: false

Lint/ShadowedArgument:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Lint/ToEnumArguments:
  Enabled: false

Lint/ToJSON:
  Enabled: false

Lint/TopLevelReturnWithArgument:
  Enabled: false

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: false

