inherit_from:
  - ./default_pending.yml

require:
  - rubocop-github
  - rubocop-performance

Bundler/DuplicatedGem:
  Enabled: true

Bundler/GemComment:
  Enabled: false

Bundler/GemFilename:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Bundler/InsecureProtocolSource:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true

Gemspec/DependencyVersion:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/DuplicatedAssignment:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RubyVersionGlobalsUsage:
  Enabled: false

GitHub/AvoidObjectSendWithDynamicMethod:
  Enabled: true

GitHub/InsecureHashAlgorithm:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/AssignmentIndentation:
  Enabled: false

Layout/BeginEndAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#indent-when-as-start-of-case
  EnforcedStyle: end

Layout/ClassStructure:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/ConditionPosition:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/DotPosition:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLineAfterMultilineCondition:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EmptyLinesAroundBeginBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocArgumentClosingParenthesis:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/IndentationConsistency:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#indentation

Layout/IndentationStyle:
  EnforcedStyle: spaces
  IndentationWidth: 2
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#default-indentation

Layout/IndentationWidth:
  Width: 2
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#default-indentation

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineContinuationSpacing:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false
