inherit_from:
  - ./rails_pending.yml

require:
  - rubocop-github-rails
  - rubocop-rails

GitHub/RailsControllerRenderActionSymbol:
  Enabled: true

GitHub/RailsControllerRenderLiteral:
  Enabled: true

GitHub/RailsControllerRenderPathsExist:
  Enabled: true

GitHub/RailsControllerRenderShorthand:
  Enabled: true

GitHub/RailsRenderObjectCollection:
  Enabled: false

GitHub/RailsViewRenderLiteral:
  Enabled: true

GitHub/RailsViewRenderPathsExist:
  Enabled: true

GitHub/RailsViewRenderShorthand:
  Enabled: true

Layout/BlockAlignment:
  Exclude:
    - "**/*.erb"

Layout/IndentationWidth:
  Exclude:
    - "**/*.erb"

Layout/InitialIndentation:
  Exclude:
    - "**/*.erb"

Layout/SpaceInsideParens:
  Exclude:
    - "**/*.erb"

Layout/TrailingEmptyLines:
  Exclude:
    - "**/*.erb"

Layout/TrailingWhitespace:
  Exclude:
    - "**/*.erb"

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - concerning

Rails/ActionControllerTestCase:
  Enabled: false

Rails/ActionFilter:
  Enabled: false

Rails/ActiveRecordAliases:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: false

Rails/ActiveRecordOverride:
  Enabled: false

Rails/ActiveSupportAliases:
  Enabled: false

Rails/AddColumnIndex:
