GitHub/RailsControllerRenderActionSymbol:
  Enabled: pending
  Include:
    - 'app/controllers/**/*.rb'

GitHub/RailsControllerRenderLiteral:
  Enabled: pending
  StyleGuide: https://github.com/github/rubocop-github/blob/main/guides/rails-render-literal.md
  Include:
    - 'app/controllers/**/*.rb'
